version: '3.4'

services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
  rag_api:  
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    # If running on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
